In [7]:
import shap
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

# Load data
X, y = load_iris(return_X_y=True)

# Train model
model = RandomForestClassifier().fit(X, y)

# Create SHAP explainer (TreeExplainer for tree models)
explainer = shap.TreeExplainer(model)

# Explain predictions for first 5 samples
shap_values = explainer.shap_values(X[:5])

print(shap_values)
# # Plot explanation for first sample, class 0
print(explainer.expected_value[0].shape, shap_values[0][0].shape, X[0].shape)
# shap.initjs()
# shap.force_plot(explainer.expected_value[0], shap_values[0][0], X[0])


[[[ 1.01095070e-01 -5.13813308e-02 -4.97137391e-02]
  [ 5.34456782e-03  1.63558886e-03 -6.98015668e-03]
  [ 2.67717132e-01 -1.21335643e-01 -1.46381489e-01]
  [ 2.95176563e-01 -1.65118615e-01 -1.30057949e-01]]

 [[ 1.04117292e-01 -6.87505937e-02 -3.53666983e-02]
  [ 2.73345671e-03 -2.74408520e-03  1.06284924e-05]
  [ 2.67717132e-01 -1.13463560e-01 -1.54253572e-01]
  [ 2.94765452e-01 -1.51241761e-01 -1.43523691e-01]]

 [[ 1.05151775e-01 -6.99921693e-02 -3.51596055e-02]
  [ 1.69897395e-03  3.98102558e-03 -5.67999954e-03]
  [ 2.67717132e-01 -1.14446101e-01 -1.53271031e-01]
  [ 2.94765452e-01 -1.55742755e-01 -1.39022697e-01]]

 [[ 1.05151775e-01 -6.99137285e-02 -3.52380464e-02]
  [ 1.69897395e-03 -1.18720844e-03 -5.11765509e-04]
  [ 2.67717132e-01 -1.13659684e-01 -1.54057448e-01]
  [ 2.94765452e-01 -1.51439379e-01 -1.43326074e-01]]

 [[ 8.83284032e-02 -4.12101529e-02 -4.71182503e-02]
  [ 1.54445678e-02 -8.81263186e-03 -6.63193596e-03]
  [ 2.69061577e-01 -1.21203547e-01 -1.47858030e-01]
  [ 

In [ ]:
import numpy as np
from lime import lime_tabular
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load data
X, y = load_iris(return_X_y=True)
y_cat = np.eye(3)[y]  # one-hot encode

# Train simple NN
model = Sequential([
    Dense(10, activation='relu', input_shape=(X.shape[1],)),
    Dense(3, activation='softmax')
])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y_cat, epochs=10, verbose=0)

# Create LIME explainer
explainer = lime_tabular.LimeTabularExplainer(X, feature_names=['f1', 'f2', 'f3', 'f4'], class_names=['setosa', 'versicolor', 'virginica'], discretize_continuous=True)

# Explain prediction for sample 0
exp = explainer.explain_instance(X[0], model.predict, num_features=4)
exp.show_in_notebook(show_table=True)


ModuleNotFoundError: No module named 'tensorflow'